# Generated by Django 5.0.14 on 2025-05-05 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clothing_images/')),
                ('category', models.CharField(choices=[('accessory', 'Accessory'), ('top', 'Top'), ('legs', 'Legs'), ('feet', 'Feet')], max_length=10)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-user'],
                'indexes': [models.Index(fields=['-user'], name='core_clothi_user_id_419527_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkinTone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skin_images/')),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-user'],
                'indexes': [models.Index(fields=['-user'], name='core_skinto_user_id_4b642d_idx')],
            },
        ),
    ]
